# Multiple Linear Regression with sklearn - Exercise Solution

You are given a real estate dataset. 

Real estate is one of those examples that every regression course goes through as it is extremely easy to understand and there is a (almost always) certain causal relationship to be found.

The data is located in the file: 'real_estate_price_size_year.csv'. 

You are expected to create a multiple linear regression (similar to the one in the lecture), using the new data. 

Apart from that, please:
-  Display the intercept and coefficient(s)
-  Find the R-squared and Adjusted R-squared
-  Compare the R-squared and the Adjusted R-squared
-  Compare the R-squared of this regression and the simple linear regression where only 'size' was used
-  Using the model make a prediction about an apartment with size 750 sq.ft. from 2009
-  Find the univariate (or multivariate if you wish - see the article) p-values of the two variables. What can you say about them?
-  Create a summary table with your findings

In this exercise, the dependent variable is 'price', while the independent variables are 'size' and 'year'.

Good luck!

## Import the relevant libraries

In [17]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import f_regression

## Load the data

In [3]:
data = pd.read_csv('real_estate_price_size_year.csv')

In [4]:
data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
5   245050.280   575.19  2006
6   265129.064   570.89  2015
7   175716.480   620.82  2006
8   331101.344   682.26  2018
9   218630.608   694.52  2009
10  279555.096  1060.36  2009
11  494778.992  1842.51  2009
12  215472.104   694.52  2015
13  418753.008  1009.25  2018
14  444192.008  1300.96  2006
15  440201.616  1379.72  2006
16  248337.600   690.54  2018
17  234178.160   623.94  2006
18  225451.984   681.07  2006
19  299416.976  1027.76  2018
20  268125.080   620.71  2015
21  171795.240   549.69  2015
22  412569.472  1207.45  2015
23  183459.488   518.38  2015
24  168047.264   525.81  2009
25  362519.720  1103.30  2018
26  271793.312   570.89  2018
27  406852.304  1334.10  2015
28  297760.440   681.07  2015
29  368988.432  1496.36  2015
..         ...      ...   ...
70  276875.632  1021.95  2009
71  181587.576   643.41  2006
72  298926.496   656.22  2015
73  211724.096   549.80  2015
74  228313.024   685.48  2018
75  286161.600   685.48  2018
76  382120.152  1183.46  2018
77  365863.936  1334.10  2006
78  251560.040   682.26  2009
79  342988.456  1188.62  2006
80  180307.216   681.07  2006
81  408637.816  1122.34  2015
82  190909.056   681.07  2006
83  282683.544   643.09  2018
84  303597.216   685.48  2018
85  376253.808  1009.25  2018
86  154282.128   479.75  2006
87  327252.112  1028.41  2009
88  211904.536   601.66  2018
89  354512.112  1236.93  2018
90  251140.656   694.52  2018
91  338078.168  1071.55  2015
92  298170.880   694.52  2015
93  266684.248   698.29  2018
94  262477.856   698.29  2006
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

## Create the regression

### Declare the dependent and the independent variables

In [5]:
y = data['price']
x = data[['size','year']]

### Regression

In [6]:
reg = LinearRegression()
reg.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

### Find the intercept

In [7]:
reg.intercept_

-5772267.017463278

### Find the coefficients

In [8]:
reg.coef_

array([ 227.70085401, 2916.78532684])

### Calculate the R-squared

In [11]:
r2 = reg.score(x,y)
r2

0.7764803683276793

### Calculate the Adjusted R-squared

In [12]:
x.shape

(100, 2)

In [13]:
adj_r2 = 1 - (1 - r2)*(x.shape[0]-1)/(x.shape[0]-x.shape[1]-1)

In [14]:
adj_r2

0.77187171612825

### Compare the R-squared and the Adjusted R-squared

Adjusted R-squared is less

### Compare the Adjusted R-squared with the R-squared of the simple linear regression

Answer...

### Making predictions

Find the predicted price of an apartment that has a size of 750 sq.ft. from 2009.

In [16]:
reg.predict([[750,2009]])

array([258330.34465995])

### Calculate the univariate p-values of the variables

In [19]:
f_reg = f_regression(x,y)

In [22]:
p_values = f_reg[1]

In [24]:
p_values = p_values.round(3)

In [25]:
p_values

array([0.   , 0.357])

### Create a summary table with your findings

In [33]:
df = pd.DataFrame(data=['size','year'],columns=['Parameter'])

In [35]:
df['Coefficient'] = reg.coef_
df['P-Value'] = p_values

In [36]:
df

Parameter  Coefficient  P-Value
0      size   227.700854    0.000
1      year  2916.785327    0.357

Answer...